### ISSUE TITLE
sass_import_get_base() different results when using data vs file compiler

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#1041]
As noted here: https://github.com/sass/libsass/issues/1035#issuecomment-88968918 these two functions have different results based on the compiler in use.

File compiler returns absolute paths, while data compiler returns relative paths for base and previous_path. Pardon my pseudo code

testfile.scss
```
@import "sub/deeptest";
```

DataCompiler
```
path:         testfile
prev.path:  stdin
prev.base: stdin
testfile.scss
path:          sub/deeptest
prev.path:  testfile
prev.base: testfile.scss
```

FileCompiler (targeted testfile directly, so only one result)
```
path: sub/deeptest
prev.path: testfile.scss
prev.base: /project/sass/testfile.scss
```

Even though both compilers negotiated the correct absolute path, data compiler only returned the relative path. IMO, these should both return absolute path for base. Thoughts?

**Comment by mgreter** [comment]
The function `sass_import_get_base` has been renamed to `sass_import_get_abs_path`. I also fixed quite a few issues with how we report included files. Since so much has changed between this report and current master, I'm going to close this now. But please feel free to re-open or preverably open a new bug if you find any other problems! Thanks!
