### ISSUE TITLE
Libsass errors on IE expression syntax

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1102]
```scss
foo {
  display:expression("inline",
    (this.innerHTML += (this.innerHTML.indexOf(",") == -1 ? ", " : "")),
    this.runtimeStyle.display = "inline");
}
```
Ruby Sass
```css
foo {
  display: expression("inline", (this.innerHTML += (this.innerHTML.indexOf(",") == -1 ? ", " : "")), this.runtimeStyle.display = "inline"); }
```
Libsass 3.0.0-beta.5
```css
Error: error reading values after 1
        on line 3 of test.scss
>> HTML += (this.innerHTML.indexOf(",") == -1 ? ", " : "")),
   ------------------------------------------^
```

**Comment by xzyfer** [comment]
Related to https://github.com/sass/libsass/issues/690

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/344

**Comment by am11** [comment]
:+1:

---

[Spoiler: Given we have custom functions, it might not be possible. On flip-side, it may be possible since it appears to me that the AST has all the required context to pull this]

IMO, at some point Sass codegens should be able to emit set of the standard CSS, v2 (and above), v3 (and above), v4 (and above) and since so forth. With those set, the compiler should error if the non-conforming pass-through CSS code is encountered. For instance, expression evaluation was ended by IE team in 2008: http://blogs.msdn.com/b/ie/archive/2008/10/16/ending-expressions.aspx and it is no longer supported in standard mode since IE8. Now in a team work, if someone used the expression evaluation, they should get the message if certain compile-time flag was set (say `--css2` or `--css3`). This is similar to how JS superset languages (sweet.js, coffeescript, typescript) are doing it. 

With that said, I think a black-list approach would be more appropriate to sniff out the vendor specific (non-prefix) tokens (such as `expression()`, `filter()` etc.) and throw.
