### ISSUE TITLE
complex units are broken via C-API

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1149]
Issue #1143 got me thinking about numbers with units and I found another bug with a similar characteristic. That is, if you pass the value you get from Sass back through the C-API then it has changed.

Here's my test case:

```js
  it("should support complex units", function (done) {
    var input = "#test1 { area: 1px * 2px / 1px;}\n" +
                "         area-fn: testing(1px * 2px) / 1px; }\n" +
                "#test2 { ratio: 20px / 2% * 1%;}\n" +
                "         ratio-fn: testing(20px / 2%) * 1%; }";
    var options = {
      data: input,
      functions: {
        "testing($value)": function(value) {
          console.log(value.getUnit());
          return value;
        }
      }
    };
    var expected = "#test1 { area: 1px; area-fn: 1px; }\n" +
                   "#test2 { ratio: 10px; ratio-fn: 10px; }\n";
    testutils.assertCompiles(options, expected, done);
  });
```

The complex units are passed as a string of the form `numerator_unit1*numerator_unit1/denominator_unit1*denominator_unit2`

However, if you pass this string back it becomes a single (illegal) unit having that same appearance but in no way acting like a complex unit as I get a compilation failure about illegal units instead of those units canceling as they should.

**Comment by chriseppstein** [comment]
Sass units are a pain in the ass. The ruby API exposes two arrays `numerator_units` and `denominator_units` for each number.

I wrote a unit parser to decompose a unit string (same form as above) into two arrays. It's part of the value helpers api.
https://github.com/sass/sass/blob/stable/lib/sass/script/value/helpers.rb

**Comment by mgreter** [comment]
Probably related https://github.com/sass/libsass/pull/1049 ... to funny, your issue is 1149 :)

**Comment by chriseppstein** [comment]
I don't think so. It seemed that complex units worked fine except when my custom function was involved. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by mgreter** [comment]
PR #1338 should bring a big improvement in regard of value handling and the C-API.
Probably still not 100% complete, but we're slowly getting there!

Does this problem still exist? Can you give some other examples how it fails for you? THX!

**Comment by saper** [comment]
Having removed extra braces in `input`:

````js
    var sass = require('node-sass');

    var input = "#test1 { area: 1px * 2px / 1px;\n" +
                "         area-fn: testing(1px * 2px) / 1px; }\n" +
                "#test2 { ratio: 20px / 2% * 1%;\n" +
                "         ratio-fn: testing(20px / 2%) * 1%; }";

    var options = {
      data: input,
      functions: {
        "testing($value)": function(value) {
          console.log(value.getUnit());
          return value;
        }
      }
    };
    var expected = "#test1 { area: 1px; area-fn: 1px; }\n" +
                   "#test2 { ratio: 10px; ratio-fn: 10px; }\n";

    
    sass.renderSync(options);
    console.log(options.result.css.toString());
````

I am getting:

````
px*px
px/%
#test1 {
  area: 2px;
  area-fn: 2px; }

#test2 {
  ratio: 10px;
  ratio-fn: 10px; }
````

so units are still strings, but they do work here and back.

Tested with node-sass master https://github.com/sass/node-sass/commit/7c15014b594f2b9e85b72cab89e2aca56762e740, libsass master as of Aug 20th https://github.com/sass/libsass/commit/0ae11a47e69164bc5ce563f51201f765d2822fb6

**Comment by hcatlin** [comment]
It's nice when you realize you fixed a bug without meaning to.

**Comment by mgreter** [comment]
I'm going to close this since there has been a lot of work done regarding C-API and value and number handling. IMHO you should be able to exchange numbers with complex units with libsass now. We also expose a `sass_op` function now that can be used to access all binary operations.

Units are indeed expected to be exchanged as strings. We do keep them as separate vectors for nominators and denominators in C++, but we need to convert this data somehow for the C-API anyway. Since C has no real support for arrays with strings of variable length, it doesn't make a big difference for the C level if we pass the unit in the current string form or use two "null terminated pseudo arrays". So if you think it makes sense to have these arrays available for numbers in node-sass, I would suggest to implement that in the binding code directly.

Please open a new issue if you find more problems! Thanks!

**Comment by saper** [comment]
I agree. I have an idea: what about storing units (via C API or maybe internally as well) as a fixed-length array of all incompatible units just with their exponents? Sure, you waste few bytes almost every time, but even if we would have implemented all units from Système International it would be only an array of 7 bytes.

**Comment by mgreter** [comment]
@saper sass accepts anything as units, not just the ones specified in css, so the max length is unknown. I don't see any benefit in this, as parsing the given unit string is as straight forward in C as any other exchange format I could possibly think of (instead of null terminated, it is '*' and '/' terminated now). Btw. the following are valid units for sass:

```scss
test: (1\65 _em--_--e0 - 2\65 _em--_--e0);
```

**Comment by saper** [comment]
> @saper sass accepts anything as units, not just the ones specified in
> css, so the max length is unknown. I don't see any benefit in this, as
> parsing the given unit string is as straight forward in C as any other
> exchange format I could possibly think of (instead of null terminated,
> it is '*' and '/' terminated now). Btw. the following are valid units
> for sass:
> 
> ```scss
> test: (1\65 _em--_--e0 - 2\65 _em--_--e0);

Excellent, thanks for pointing this out :)
