### ISSUE TITLE
3.2.1 release

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1150]
We'd originally planned to ship 3.2.1 with a handful of [minor features and patches](https://github.com/sass/libsass/milestones/3.2.1) once the 3.2.0 dust settled but it appears we've had some show stoppers that weren't caught in our 6 rounds of beta releases.

I propose we ship 3.2.1 asap addressing these issues
- [x] #1047
- [x] #1049
- [x] #1055
- [x] #1138
- [x] #1140
- [x] #1144
- [x] #1145 (#1146, #1147)
- [x] #1148
- [x] https://github.com/sass/sassc/pull/105

Thoughts and feels? @mgreter @hcatlin

**Comment by xzyfer** [comment]
Tracking this in https://github.com/sass/libsass/milestones/hotfix

**Comment by mgreter** [comment]
Do you want to include the queued and ready PRs for 3.2.1. I basically just wanted to rebase them all when I get to it, but otherwise they should be ready! But we can also do two short follow up releases.

**Comment by xzyfer** [comment]
I'd rather wait til the dust settings before shipping the 3.2.1 PRs. I'd created a hotfix milestone to track these critical issues.

**Comment by mgreter** [comment]
We have the following PRs pending:

- #1055 - Relax compact error to warning -> how long we want to keep it an error?
- #1049 - Fix mathematical operations with different/complex units -> probably #1149
- #1047 - Fix `str-slice` function to work with utf8 strings -> Code looks cleaner and passes spec test
- #1138 - Fix order of top nodes -> Actual fix is rather trivial

- #1046 - Implement handling of nested `:not` pseudo selectors -> minor feature to pass a spec
- #1050 - Fix separator preserving with rest args -> needs check since we did some work there IMO

IMO we should at least consider the first 4 PR for the next minor release!

**Comment by xzyfer** [comment]
I think we should abandon #1055 in favour of removing all traces to `compact`. I expect the amount of people relying on this is approaching 0.

I'm :+1: to shipping the other three. The last two can wait IMO.

**Comment by mgreter** [comment]
I can rebase to get a new CI run ...

**Comment by xzyfer** [comment]
I've renamed the 3.2.1 milestone to 3.2.2
I've renamed the hotfix milestone to 3.2.1
I've reassigned #1049, #1047, #1138 to the 3.2.1

**Comment by xzyfer** [comment]
:ship:

**Comment by xzyfer** [comment]
@mgreter whilst I have your attention can you please jump into Slack and check my message? :)

**Comment by onedayitwillmake** [comment]
Any word on the selector functions?

**Comment by xzyfer** [comment]
@onedayitwillmake this a hotfix release to address some critical issues that came up in 3.2.0.

Selectors will land in our next major release.
