### ISSUE TITLE
Any plans to add trace_selectors support?

### ISSUE THREAD

**Issue by drone1** [sass/libsass#1222]
Added to sass in version 3.1.6:

When set to true, emit a full trace of imports and mixins before each selector. This can be helpful for in-browser debugging of stylesheet imports and mixin includes. This option supersedes the :line_comments option and is superseded by the :debug_info option. Automatically disabled when using the :compressed output style.

**Comment by xzyfer** [comment]
No plans at the moment.

**Comment by drone1** [comment]
Would you help me understand why not? Seems like a lot of what people complain about with regard to mixins being difficult to debug goes away if you have a feature like this.

**Comment by xzyfer** [comment]
Currently you are the only person asking for this. This issue is the first time I've heard of this feature. These two things tell me this is a very low priority. Certainly lower than getting feature parity with Ruby Sass.

We may eventually get to this but it's not a priority for anyone. We're open to pull requests.

**Comment by drone1** [comment]
Roger that. Thanks.

**Comment by mgreter** [comment]
I think we should close this. IMO this would first need to be supported by ruby sass.

**Comment by xzyfer** [comment]
:+1:

**Comment by mgreter** [comment]
If it is then my bad! Can someone confirm?

**Comment by mgreter** [comment]
I created a collective ticket to keep track of this and other "non-urgent" feature requests, in order to keep the issue tracker a bit more clean for the more 1st aid issues. I would like to encourage everybody interested in this particular feature to add their comments into this closed issue anyway.

Thanks for your understanding and your contribution!

**Comment by DerTieran** [comment]
Just wanted to add my **+1** for this feature.

Not sure what you consider as *"supported by Ruby Sass"*.
You can't add it as a command line option *(I think)*, but it is supported by [`sass`](https://github.com/sass/sass/blob/5280f2335cf331beb3f6c537e292493d0116567b/doc-src/SASS_CHANGELOG.md#316).
*I used it with compass for example.*

Would be awesome to have this in `libsass` because it really helps when using some mixins.
