### ISSUE TITLE
[Feature request] Add Stream(ing) support for input and output

### ISSUE THREAD

**Issue by driekus77** [sass/libsass#1414]
I looked at your code shortly but can not figure out if its hard to implement: Stream(ing) support.

A function like CompileFile in the libsass-net using the sass file context in libsass. Correct me if I'm wrong but both input and output are handled in memory. When libraries are getting bigger and bigger this can become a problem. Again I don't know if the compiler can use C++ streams but IMHO its worth to investigate.

Using streams is nicer for the client side because the client programmer can decide what stream to use: memory stream (C++ stringstream) or file stream (C++ fstream) or other kind of streams.

I'm very curious what your guys think about this feature request!

Kind regards,
Henry

**Comment by saper** [comment]
We also support "data" context, where source is provided as the user-supplied memory buffer. Would that work for your case?

**Comment by driekus77** [comment]
"data context" only counts for input?

I was more thinking in the line of C++ streams:
void CompileToStream(std::istream* scssInput, std::ostream* cssOutput, std::ostream* srcMapOutput = nullptr);

But I can imagine that you want to keep the C API clean of C++?

Technical indept (Please correct me if I'm wrong):
Input Stream => (Pre)Lexer => Parser(s) => Abstract Syntax Tree (AST) => Compiler => Output Stream.

In above workflow only the AST will need extensive memory. The streaming will be "Read/Write and forget".
But it totally depends on if one of the other components needs (in memory) reference to the input or output data.

Next added feature is that C++ streaming can give you locale/encoding conversion support for free.

**Comment by mgreter** [comment]
There are a few use cases where we could profit a little from a streaming parser, but in most cases we need to keep a copy around anyway. This is mostly related to source-maps, since there is an option to even embed all inputs into the source-map. Even when we generate source-maps without embedding the inputs directly, we need to keep copies around for each identifier token (which could be optimized, so it would not use as much memory as keeping the whole input around and just use start and end pointers, as we do now).

So I don't think we will ever support this, also since we do not offer any C++ API. Although the CSS specs clearly state that you always know what to parse by looking at the "next" two bytes ...

As for encoding, C++ streams do not give encoding out of the box. They will give a nice interface, but you still need to some proper implementation like `iconv`. Once we are that far it is also not very hard to do the encoding/decoding on the in memory buffer.

**Comment by mgreter** [comment]
I vote to close this, since we will probably never implement it.

**Comment by xzyfer** [comment]
Agreed.
