### ISSUE TITLE
-DDEBUG should not add unconditional debug output

### ISSUE THREAD

**Issue by saper** [sass/libsass#1518]
I have `-DDEBUG` in my compiler flags due to building of the debug module of node and it looks like `libsass` generates a lot of debugging output automatically.

There should be a runtime option to explicitly set the debug level (default: off) to keep libsass quiet by default.

**Comment by mgreter** [comment]
Not sure if it is really that unreasonable for libsass to produce debug output when `DEBUG` compile flag is set. Each implementer that compiles libsass can set that option accordingly if desired. So I feel it's ok the way it is now, although a more sophisticated debug interface would be desirable (PR always welcome, but as such not a high prio).

I added this to the [wish-list] [1] ticket, since I think this issue is actually more about a better and more configurable debug build itself. Currently the DEBUG flag only really debugs the extend step and nothing else ...

[1]: https://github.com/sass/libsass/issues/1892

**Comment by xzyfer** [comment]
I noticed this broke in 3.3.3. I use `DEBUG_PRINTLN` a lot. This made me sad.

**Comment by xzyfer** [comment]
Maybe I'm misunderstanding, and this is not related to the `DEBUG_LVL` used by `debug.hpp`.

**Comment by mgreter** [comment]
I guess it's related and it was unknown to me we already had something for starters in debug.hpp. But I'm still pretty sure this is only used in extend step.
