### ISSUE TITLE
Incorrectly allowing functions to be defined in control directives or mixins

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1550]
Originally reported on Twitter - https://twitter.com/kaelig/status/643584415789154304

Functions may not be defined within control directives or mixins but LibSass allows it i.e.

```scss
@if (true) {
  @function foo() {
    @return 'foo';
  }
}
```

Should produce the following error but does not

```
Error: Functions may not be defined within control directives or other mixins.
```

**Comment by xzyfer** [comment]
Other notable cases where we should, but don't throw this error.

```scss
@mixin foo() {
  @function foo() {
    @return 'foo';
  }
}
```
```scss
$i: 1;
@while $i == 1 {
  @function foo() {
    @return 'foo';
  }
  $i: $i + 1;
}
```
```scss
@each $i in (1) {
  @function foo() {
    @return 'foo';
  }
}
```
```scss
@for $i from 1 through 2 {
  @function foo() {
    @return 'foo';
  }
}
```

**Comment by saper** [comment]
Nice enhancement :) Closures, anyone?

**Comment by xzyfer** [comment]
I like it, but it's not Sass :(

**Comment by xzyfer** [comment]
Turns out this also affects mixins

```scss

@mixin foo() {
  @mixin bar() {
    @return 'foo';
  }
}
```

**Comment by saper** [comment]
Let's open an enhancement proposal :)

**Comment by xzyfer** [comment]
https://twitter.com/chriseppstein/status/643584546298986496

**Comment by perplexes** [comment]
Just ran into this with https://github.com/Igosuki/compass-mixins/issues/34 / https://github.com/Igosuki/compass-mixins/pull/67. It's trying to define `compact` if it doesn't exist. Since compact was stripped from libsass, this is needed to put it back in, in a version independent way.

Currently (as of b2a3d98ed384d2d19aa79157d08fa21c3e8043e0) function definition is scoped to the control block, breaking this usage (`@if not(function-exists(compact)) { ....`). Causing this funny behavior: https://gist.github.com/perplexes/e0e75f00b3772f2bf643. It seems to not register with the globals, so even `function-exists` breaks within the block.

Current work-around is to just remove the if statement (since in my codebase I know we need it). Any suggestions on what compass-mixins can do, though? Maybe a function-if-not-exists directive?
