### ISSUE TITLE
Support for @import globbing ala Sass-globbing

### ISSUE THREAD

**Issue by benfrain** [sass/libsass#156]
Would it be possible to support file globbing import statements?

E.g. 

```
@import "_partials/custom/**/*";
@import "_partials/_modules/**/*";
```

I tend to make LOT'S of low specificity partials where import order is unimportant and Globbing let's me easily create them without having to continually specify another import.

Any chance we could see support of import globbing?

**Comment by tschwartz** [comment]
I would suggest using something like https://www.npmjs.com/package/gulp-include (there's most likely something similar for Grunt). I use it for all of my dependency management so that my Gulp setup doesn't need to have that logic baked into it and the mechanism for doing so is consistent across HTML, SCSS and JavaScript. For example:

common.scss
```
//= require ../../../bower_components/normalize.css/normalize.css
//= require '_helpers.scss';
//= require '_base.scss';
//= require '_typography.scss';
//= include ../components/common/**/_*.scss
```

scss.js
```
gulp.task('scss', function() {
  return gulp.src([
      './src/public/scss/**/*.scss'
    ])
    .pipe(plugins.include())
    .pipe(plugins.sass())
    .pipe(plugins.autoprefixer())
    .pipe(plugins.cssmin())
    .pipe(plugins.rename(function(path) {
      path.extname = '.min.css';
    }))
    .pipe(gulp.dest('./dist/public/css/'));
});
```

**Comment by xttn** [comment]
+1
