### ISSUE TITLE
3.3 API Integration

### ISSUE THREAD

**Issue by absalomedia** [sass/libsass#1627]
The API documentation here: https://github.com/sass/libsass/wiki/API-Documentation talks about sass_context.h & sass_interface.h - both of which I'm using in various integrations.

As 3.3 restructures everything under the includes directory, the API documentation is out of date. What's the new way of referencing the API?

**Comment by mgreter** [comment]
Headers were move to `sass` subfolder, so change `sass_context.h` to `sass/context.h` (and other sass headers accordingly). You may also need to give the proper include paths to compile, since they are no longer in the same folder as the source files. The master docs are now included in the main git repo.

**Comment by absalomedia** [comment]
OK. Managed to wrangle my PHP & HHVM integrations up to 3.3.0..  Still working on the Nginx Libsass 3.3 edition..

When will the API documentation be updated?

**Comment by mgreter** [comment]
https://github.com/sass/libsass/pull/1639
