### ISSUE TITLE
Spacing create a error

### ISSUE THREAD

**Issue by ChrisCinelli** [sass/libsass#1761]
We usually add a space after columns, however every now and then somebody forget it. 
It was working fine with node-sass 3.3.3 but after upgrading to node-sass 3.4.2  we get a new error compiling this code:
```
.abc
  margin:40px 0
```
I tested also in http://medialize.github.io/playground.sass.js/ (libsass 3.3.1) and it returns the same error:

```
Error: Invalid CSS after "  margin:": expected pseudoclass or pseudoelement, was "40px 0 {} }"
        on line 2 of stdin
>>   margin:40px 0 {} }
   --------^


{
  "status": 1,
  "file": "stdin",
  "line": 2,
  "column": 9,
  "message": "Invalid CSS after \"  margin:\": expected pseudoclass or pseudoelement, was \"40px 0 {} }\""
}
```

In http://sassmeister.com/ it compiles to:
```
.abc {
  margin: 40px 0;
}
```

**Comment by xzyfer** [comment]
LibSass in a implementation of the Sass language created by Ruby Sass. Since Ruby Sass acts the same way we're doing the correct thing. If you think this is a bug with Sass please open an issue with Ruby Sass https://github.com/sass/sass/issues.

Sassmeister uses an older version of LibSass that incorrectly failed to error in this case.
