### ISSUE TITLE
Prefix constants with a prefix to prevent collisions

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1802]
> I think we should just rename all constants and prefix them with something like LIBSASS_ to avoid issues like the SEC one. Otherwise it'll be the endless chase...
>https://github.com/sass/libsass/pull/1782#issuecomment-166031233.

I believe we start prefixing some constants with `SASS_` 3.3. We should finish the job.

**Comment by mgreter** [comment]
IMO it is okay as it is now. So far only C-API stuff is prefixed with `SASS_`, since we have a `Sass` namespace on the C++ side. The issues we had were due to `using namespace std` which has been dropped, so it should be ok now. I really would like to encourage to work with namespaces in C++ (i.e. Units now live in `SassUnit` namespace). There will always be compiler quirks as ie. the one with `std::round` that surfaced on cygwin when we prefixed all identifiers from std.

**Comment by saper** [comment]
What about just having `LIBSASS_` prefix on all our constants?

C++ namespaces will not solve `SEC` issue afaik (the preprocessor will still try to expand it!)

**Comment by mgreter** [comment]
I absolutely would hate that, but I guess that's already clear. So we would have `Sass::SassUnit::LIBSASS_SEC` just because one compiler can't keep it together? I say let's keep it as it is with the `#undef SEC` since that macro should never be defined in the first place!

**Comment by saper** [comment]
It is not the compiler, those are the header files. If you don't like it we can drop SassUnit, since that's a bit too much. it's a known problem in the C world and most libraries try to namespace like this, this is nothing unusual. Windows is also adding random symbols defined here and there, you might by lucky with one SDK or version setting, but not with another. We can't change a whole world.

**Comment by QuLogic** [comment]
Is the `LIB` part really necessary though?

**Comment by mgreter** [comment]
So I took the pleasure to install smartos on a virtual machine, which took me 3 hours [due to a bug] [1] in their installer :facepunch: Once I had it running it took me another hour to figure out how to [install] [2] gcc (`pkgin in scmgit-base gcc47; export PATH="$PATH:/opt/local/gcc47/bin/"`). Once I was that far it took me a couple of minutes to figure out how to avoid these macros to be exported:

In src/units.cpp:
```
#undef __EXTENSIONS__
#include <stdexcept>
#include "units.hpp"
```

This makes all `#undef` obsolete and the file compiles correctly. This needs to be place into every compile unit before any system header includes. This is much easier to apply and I think we should create a common `sass.hpp` header that must be the first include in every compilation unit.

Will try to find out what that `__EXTENSIONS__` define actually is ...

[1]: https://github.com/joyent/smartos-live/issues/506
[2]: https://wiki.smartos.org/display/DOC/Installing+pkgin

**Comment by mgreter** [comment]
@QuLogic we already export stuff under the `SASS_` prefixes with the C-API, so mixing C and C++ here would even be worse, since we ie. already have a SASS_STRING or SASS_ERROR on the C-API.

**Comment by mgreter** [comment]
I have create a PR which fixes the issue when I test it on `SunOS smartos 5.11 joyent_20160108T173524Z i86pc i386 i86pc`. I suspect [this bug] [1] or some similar stuff going on:

> C++ options for C++0x / GNU-extended C++0x (-std=c++0x, -std=gnu++0x) 
should probably be treated like those for c99/gnu99, since C++0x uses the 
C99 library (whereas C++98/C++03 uses the C90+AMD1 library).

We pass `-std=c++0x` so it should probably not use any gnu extensions!?

[1]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40411

**Comment by mgreter** [comment]
I'm closing this as it should not be needed. I jumped through hoops to ensure this is fixed now!
