### ISSUE TITLE
Merge media queries with same conditions

### ISSUE THREAD

**Issue by manuel-di-iorio** [sass/libsass#1840]
Use case (scss):

	body {
		font-size: 15pt;
		
		@media (max-width: 40em) {
			font-size: 13pt;
		}
	}

	header {
		font-size: 17pt;
		
		@media (max-width: 40em) {
			font-size: 15pt;
		}
	}

This will be compiled in nested mode to:

	body {
	  font-size: 15pt; }
	  @media (max-width: 40em) {
		body {
		  font-size: 13pt; } }

	header {
	  font-size: 17pt; }
	  @media (max-width: 40em) {
		header {
		  font-size: 15pt; } }

Same with compressed output:

    body{font-size:15pt}@media (max-width: 40em){body{font-size:13pt}}header{font-size:17pt}@media (max-width: 40em){header{font-size:15pt}}

As you can see, as the file will become more complex, as more media queries with same conditions there will be, not good if you want to compress your css a lot, but still using the powerful syntax of sass :)

**Comment by mgreter** [comment]
Ruby sass does not merge these either, so nothing libsass could do here!
I'm also very sure that this is logically not possible, since we don't know where to put the selectors in between the two to be merged media query blocks. Where should `header { font-size: 17pt; }` go? Before or after the merged media-query block? This is because the `header` selector has the same specificity in all three occurrences, so the order is very important!

**Comment by xzyfer** [comment]
@manuel-di-iorio propose this feature to the Ruby Sass team if you think it should implemented.

**Comment by manuel-di-iorio** [comment]
@xzyfer Yup, I'll do thanks :+1:
