### ISSUE TITLE
libsass fails silently on missing functions

### ISSUE THREAD

**Issue by peschee** [sass/libsass#2014]
When referencing an undefined, custom function in libsass, the compilation fails silently. Shouldn't referencing missing functions throw errors and thus notify you of possible code issues on compile time?

I have created an example gist http://www.sassmeister.com/gist/8be6baa89b9839046ce792181a0a4e64

**Comment by xzyfer** [comment]
LibSass is an implementation of the Sass language. Our goal is to be 100$ compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue. 

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by xzyfer** [comment]
For reference this is a feature of Sass. Sass functions have the same syntax and CSS functions so if the function you're calling doesn't exist in Sass we assume you meant to call a CSS functions i.e. `url()`, `rgb()`, etc...

**Comment by peschee** [comment]
Thanks for letting me know @xzyfer Wasn't aware of this, your arguments make sense though. It just makes it a bit trickier when refactoring your code.
