### ISSUE TITLE
Abort thrown with smart quote

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2016]
```sass
$_: ___((Classes and IDs must follow a specific grammar. And this thing here doesn’t.));
```
Ruby Sass
```
Error: Invalid CSS after "...pecific grammar": expected ")", was ". And this thin..."
        on line 1 of test.scss
  Use --trace for backtrace.
```
LibSass 3.3.5
```
Assertion failed: (utf8_validate(str)), function emit_string, file src/json.cpp, line 1144.
[1]    51273 abort      ~/Projects/Sass/sassc/bin/sassc test.scss
```
Spec added https://github.com/sass/sass-spec/pull/776

**Comment by mgreter** [comment]
This works correct for me if I save the input as valid utf8.
I only see this if I save it with wrong encoding, so what should be done here?

**Comment by xzyfer** [comment]
I'm not sure to be honest. IIRC Ruby Sass has some logic around file encodings i.e. if it encounters a unicode character it inserts `@charset "utf-8";` automatically.

I wonder if it assumes all files are utf-8 by default... @chriseppstein may have some insight.

**Comment by mgreter** [comment]
The error happens because the byte sequence is found to NOT be valid utf8. So what should we do? This can happen because of invalid input but also if we do a substring not accounting for utf8 sequence (meaning there is a chance a multibyte utf8 character gets "split in half"). We cannot do much about the first and I only would count the later as a bug (fixed a [few of them] [1] already, as with i.e. with error reporting).

[1]: https://github.com/sass/libsass/commit/3467e6013a8c63d2ddb645b352e79cfe10a2f907
