### ISSUE TITLE
Regression with @extends and @media

### ISSUE THREAD

**Issue by paulfalgout** [sass/libsass#2019]
I have a feeling this won't be a popular bug, but it seems like a different edge case from https://github.com/sass/libsass/issues/2009 and https://github.com/sass/libsass/issues/2007

I wasn't seeing this in libsass `v3.3.2`

I think I've isolated the problem to this:
```
@mixin mq($points, $directions: min, $dimensions: width) {
    $query: '';
    @for $i from 1 through length($points) {
        $query: $query + ' and (#{nth($directions, $i)}-#{nth($dimensions, $i)}: #{nth($points, $i)})';
    }

    @media screen #{$query} {
        @content;
}
}

%color {
    color: #F00;
}


.foo {
    @extend %color;
    padding: 10px;

    @include mq($bp-medium, min, width) {
        padding: 30px;
    }
}
```

and getting "You may not @extend an outer selector from within @media"

**Comment by mgreter** [comment]
Your sample (once I added the missing pieces) [compiles correctly] [1]!
Closing since no version was stated, so I guess it was not the latest!

[1]: http://libsass.ocbnet.ch/srcmap/#JGJwLW1lZGl1bTogImZvbyI7CkBtaXhpbiBtcSgkcG9pbnRzLCAkZGlyZWN0aW9uczogbWluLCAkZGltZW5zaW9uczogd2lkdGgpIHsKICAgICRxdWVyeTogJyc7CiAgICBAZm9yICRpIGZyb20gMSB0aHJvdWdoIGxlbmd0aCgkcG9pbnRzKSB7CiAgICAgICAgJHF1ZXJ5OiAkcXVlcnkgKyAiIGFuZCAoI3tudGgoJGRpcmVjdGlvbnMsICRpKX0tI3tudGgoJGRpbWVuc2lvbnMsICRpKX06ICN7bnRoKCRwb2ludHMsICRpKX0pIjsKICAgIH0KCiAgICBAbWVkaWEgc2NyZWVuICN7JHF1ZXJ5fSB7CiAgICAgICAgQGNvbnRlbnQ7Cn0KfQoKJWNvbG9yIHsKICAgIGNvbG9yOiAjRjAwOwp9CgoKLmZvbyB7CiAgICBAZXh0ZW5kICVjb2xvcjsKICAgIHBhZGRpbmc6IDEwcHg7CgogICAgQGluY2x1ZGUgbXEoJGJwLW1lZGl1bSwgbWluLCB3aWR0aCkgewogICAgICAgIHBhZGRpbmc6IDMwcHg7CiAgICB9Cn0g

**Comment by paulfalgout** [comment]
Ah the sourcemap inspector will be useful.  I guess I need to trace down the issue more.

With 0 code changes I did a fresh install of `gulp-sass` `~2.2.0` which has a dependency on `node-sass` of `^3.4.1` and `node-sass` `3.5.x` recently updated `libsass` such that I am now using `3.3.5`

If I force `gulp-sass` to use `node-sass` `3.4.1` which uses `libsass` `3.3.2` this error goes away

**Comment by paulfalgout** [comment]
So perhaps I'm running into a legitimate error that wasn't thrown in the earlier versions.  Upon closer inspection of the error I was looking at the wrong line trying to make an example: Here's what breaks:
[example](http://libsass.ocbnet.ch/srcmap/#QG1peGluIG1xKCRwb2ludHMsICRkaXJlY3Rpb25zOiBtaW4sICRkaW1lbnNpb25zOiB3aWR0aCkgewogICAgJHF1ZXJ5OiAnJzsKICAgIEBmb3IgJGkgZnJvbSAxIHRocm91Z2ggbGVuZ3RoKCRwb2ludHMpIHsKICAgICAgICAkcXVlcnk6ICRxdWVyeSArICcgYW5kICgje250aCgkZGlyZWN0aW9ucywgJGkpfS0je250aCgkZGltZW5zaW9ucywgJGkpfTogI3tudGgoJHBvaW50cywgJGkpfSknOwogICAgfQoKICAgIEBtZWRpYSBzY3JlZW4gI3skcXVlcnl9IHsKICAgICAgICBAY29udGVudDsKICAgIH0KfQoKJGJwLW1lZGl1bTogKDY0MC8xNikgKiAxZW07CiRicmFuZGluZy1jb2xvcjogIzA1ODJEQTsKCi5zY3JlZW5pbmdfX2l0ZW0gewogICAgQGluY2x1ZGUgbXEoJGJwLW1lZGl1bSwgbWluLCB3aWR0aCkgewogICAgICAgICYuaGlnaGxpZ2h0IGxhYmVsIHsKICAgICAgICAgICAgQGV4dGVuZCAlYmMtYm94LXNoYWRvdy1pbnNldDsKICAgICAgICB9CiAgICB9CiB9CgolYmMtYm94LXNoYWRvdy1pbnNldCB7CiAgICBib3gtc2hhZG93OiBpbnNldCAwIDAgMCAxcHggJGJyYW5kaW5nLWNvbG9yOwp9Cg==) @mgreter is this specifically what the error is addressing or this a regression?

With libsass `3.3.2` it would output with no error:
```
.screening__item.highlight label {
  box-shadow: inset 0 0 0 1px #0582DA;
}
```

**Comment by mgreter** [comment]
Now take that snippet and enter into http://www.sassmeister.com/ to see what official ruby sass thinks about the code snippet (hint: the same as libsass does now). So this was fixed in libsass recently.
