### ISSUE TITLE
Mixins may not be defined within control directives or other mixins

### ISSUE THREAD

**Issue by AlexisVK** [sass/libsass#2030]
<pre><code>@mixin foo() {
    ....
    @mixin bar() {
        ...
    }
}</code></pre>

Doesn't compile anymore

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by xzyfer** [comment]
This code was never valid Sass. It previously worked due to a bug, that bug has been fixed.

**Comment by glen-84** [comment]
@xzyfer,

I have the same issue, and it compiles without errors using Sass 3.4.22:

```
vagrant@debian-wheezy:~/test-ruby-sass$ sass pages.scss > out.css
DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.
vagrant@debian-wheezy:~/test-ruby-sass$
```

Did this change in a later version of Sass? I got `3.4.22` when running `gem install sass`.

**Comment by xzyfer** [comment]
Without any code there isn't any thing I can say to you. If code compiles with Sass but not LibSass then it is a bug, please open a issue. Before doing so make sure code compiles with the latest LibSass which is available via www.sassmeister.com

**Comment by glen-84** [comment]
@xzyfer https://github.com/sass/libsass/issues/2095
