### ISSUE TITLE
Quotes included in concatenated string output in 3.3.6

### ISSUE THREAD

**Issue by ashclarke** [sass/libsass#2080]
Hi, I've recently updated from node-sass 3.4.2 (**libsass 3.3.2**) to 3.7.0 (**libsass 3.3.6**).

A change is introduced whereby the result of a string concatenation function I have (SC) now returns 2 double quotes, the initial value of the returned var in SC, in certain cases. This results in output such as `.space-""-inset {`.

I've created a sample gist on sassmeister that illustrates what is happening. I can workaround the problem, but I'm not sure if it is considered the "correct" way. Line 24-28 explains this.

http://www.sassmeister.com/gist/d3a552b377ab34d4f53efdb873e95284

I don't believe this to be a bug; perhaps more of a question about how the string interpolation works or has changed in newer versions.

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. Something is considered a bug if we produce different output to the official Sass compiler.

In this case the official Sass compile errors with your code. 

>I don't believe this to be a bug

Technically there is a bug in LibSass that allows this code to compile. As for the quote issue, I can't determine if there is a bug with handling quotes because I cannot get your code to compile with official Sass compiler to compare the output.

>how the string interpolation [...] has changed in newer versions

Every new release of LibSass brings us closer to behaving like the official Sass compiler. The release notes for each release covers the specific changes.

***

It's worth being aware that you should always assert that your code is valid Sass as far as the official Sass compiler is concerned. I cover this extensively in a recent blog post - https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.6jh3adpe0

***

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by ashclarke** [comment]
Ah ok, I've updated the gist to remove the extraneous `;` and I now see the error 
```
Invalid CSS after ".space-": expected selector, was """-inset"
```
when switching to use Sass 3.4.21 as the compiler.

Thanks for the pointers and apologies for the misunderstanding. More :coffee: required!

**Comment by xzyfer** [comment]
You might be interested to know I was able to derive two separate LibSass issues from your code sample - #2081 and #2082

**Comment by ashclarke** [comment]
Thanks! Glad I could help out (even if in such a roundabout way! :smile:)

**Comment by xzyfer** [comment]
The correct fix for code is

```diff
-$string: $string#{$separator}#{$item};
+$string: #{$string}#{$separator}#{$item};
```

You should always `#{}` your variables when output them to css i.e. in properties of selectors.

**Comment by ashclarke** [comment]
Ok, thanks. I just discovered that it is possible to define `$string: null;` to "solve" the problem, but it is clear now that that is a workaround to missing the interpolation when redefining `$string` later.
