### ISSUE TITLE
Using a compass transition results in an Undefined operation error

### ISSUE THREAD

**Issue by cldwalker** [sass/libsass#2097]
Hi. While using sassc 3.3.0 with libsass 3.3.4 and compass 1.0.3,  I'm running into the following exception:
```
Error: Undefined operation: "prefix-usage(browser-prefixes(browsers()), css-transitions, (full-suppor
t: true), (partial-support: true)) gt 0.1".
        on line 324 of vendor/compass/compass/_support.scss
>>   @if $usage > $threshold {
   ------^
```
I've narrowed the offending scss to:

```scss
.ng-hide-add,
.ng-hide-remove {
    @include transition(all 300ms ease-out);

    display: block !important;
    opacity: 1;
}
```
I built the scss with `sassc -m -I vendor/scss -t nested scss/main.scss resources/public/css/`

I was going to report this on sassc but noticed that the same issue is being picked up by a sassc alternative in https://github.com/sass/sassc-ruby/issues/36 . Let me know if there's more info I can provide. Thanks!

**Comment by xzyfer** [comment]
Compass cannot work with LibSass. It touch some Ruby Sass internals which
obviously can't happen in c++. I suggest looking at autoprefixer or
bourbon.io instead.

**Comment by cldwalker** [comment]
I misspoke in the first sentence but I am using it with sassc with the command I indicated above. More about sassc  version:
```
$ sassc --version
sassc: 3.3.0
libsass: 3.3.4
sass2scss: 1.0.5
```

**Comment by xzyfer** [comment]
As previously stated you cannot use compass with LibSass. The error your getting is due to compass trying to use a Ruby function that it magically adds to Ruby Sass. LibSass is C++ not Ruby so this function doesn't exist causing your error. There is no way to fix this, you simply cannot use compass and LibSass together.

Bourbon.io and autoprefix are much better, more modern alternatives to compass css3 mixins.

**Comment by cldwalker** [comment]
@xzyfer Gotcha. Thanks for the suggestions
