### ISSUE TITLE
No error on duplicate mixin

### ISSUE THREAD

**Issue by iddekingej** [sass/libsass#2145]
Sass:
```
@mixin xx($p_a)
{
	a:$p_a;
}


@mixin xx($p_b)
{
	b:$p_b;
}

.x{
	@include xx("xx");
}
```

Output:
.```
x {
  b: "xx"; }

What expect: duplicate mixin error message  

compiles with sassc version:
sassc: 3.3.6-11-g077a-dirty
libsass: 3.3.6-91-g96ff0-dirty
sass2scss: 1.0.6

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass
