### ISSUE TITLE
please can someone kind provide a compiled binary of libsass

### ISSUE THREAD

**Issue by sukexero** [sass/libsass#2209]
Hi.
I need compiled .exe sass lib, I just don't want to go through the whole trouble of installing VS 2013 just for one purpose. I just need to use sass with php without installing ruby and other dependencies that's all I want.
please help me.

**Comment by nschonni** [comment]
https://github.com/sass/libsass/blob/master/docs/implementations.md#php

**Comment by sukexero** [comment]
Hi nschonni
I still need to compile libsass right? plz can you give me the compiled library?

**Comment by mgreter** [comment]
Here you go: https://github.com/sass/perl-libsass/wiki/Standalone-Executable-and-MSI-Installer

**Comment by mgreter** [comment]
Libsass and sassc installer is here => http://libsass.ocbnet.ch/installer/

**Comment by sukexero** [comment]
thank you very much mgreter I really appreciate it.

**Comment by Borislav69** [comment]
@sukexero 
were you able to successfully install those .msi installers?

@mgreter 
I tried to install on 3 different machines running windows 7 sp1 without any success! always get error "could not access network location" do have another installer or perhaps just the executable for sass compiler?

maybe here isn't the right place to ask this question but do you guys have any Idea why the maintainers of https://github.com/sass/sassc don't provide official binaries and why they want every body to install VS and compile themselves?

**Comment by mgreter** [comment]
@Borislav69 you can extract the files from the MSI installer with i.e. 7zip directly. I've installed it on various PCs with varying windows versions and never seen that error. We don't provide official binaries with sassc mainly because of lack in resources/manpower, simple as that! You can also [compile] [2] it via [mingw] [1], which is a much leaner dependency than VS!

[1]: https://github.com/sass/libsass/blob/master/docs/build-with-mingw.md
[2]: https://github.com/mgreter/libsass-msi-installer/tree/master/compile
