### ISSUE TITLE
Trailing semicolon elided in "compressed" style (3.4.x regression)

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#2461]
The following .scss source has its trailing ';' elided with `-t compressed` but not with `-t compact`:
```scss
@provide 'foo';
```

Even for such an imaginary at-rule (comes from GSS, btw), it [seems that the spec doesn't allow for this semicolon to be stripped](https://www.w3.org/TR/css-syntax-3/#parser-diagrams) for at-rules that don't have a body.

This worked fine in 3.3.2 and is broken in 3.4.0 & 3.4.5

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass
