### ISSUE TITLE
Comparison table missing Libsass 3.4?

### ISSUE THREAD

**Issue by esr360** [sass/libsass#2473]
I am experiencing inconsistencies between Ruby Sass 3.4, and LibSass 3.4. In order to pinpoint why these inconsistencies may be happening,  I took to the [Sass Compatibility Page](http://sass-compatibility.github.io/) as instructed. This page does not compare Ruby Sass 3.4 with LibSass 3.4, so I'm not sure where to find the "few incomplete edges which we are aware of" that are mentioned.

Is there a publicly accessible list of the incomplete edge cases that you are aware of, to see if any are the same as the edge cases I am experiencing?

**Comment by xzyfer** [comment]
This issue tracker is all the known inconsistencies. Any inconsistenty that
doesn't have an issue (open or closed) is unknown.

On 11 Sep. 2017 4:38 pm, "Edmund" <notifications@github.com> wrote:

I am experiencing inconsistencies between Ruby Sass 3.4, and LibSass 3.4.
In order to pinpoint why these inconsistencies may be happening, I took to
the Sass Compatibility Page <http://sass-compatibility.github.io/> as
instructed. This page does not compare Ruby Sass 3.4 with LibSass 3.4, so
I'm not sure where to find the "few incomplete edges which we are aware of"
that are mentioned.

Is there a publicly accessible list of the incomplete edge cases that you
are aware of, to see if any are the same as the edge cases I am
experiencing?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sass/libsass/issues/2473>, or mute the thread
