### ISSUE TITLE
Cannot download v4.5.3 (linux-x64-59_binding.node)

### ISSUE THREAD

**Issue by ktanteo** [sass/libsass#2489]
This error just popped up on our test server today. Everything was working fine just yesterday. Can anyone shed a light on this?

```
    Checksums empty
    Now using node v9.0.0
    Now using node v9.0.0
    ---NPM version---
    5.5.1
    v9.0.0
    ...
    ...
    ...
    ---Install NPM dependencies ---
    
    > node-sass@4.5.3 install /build/node_modules/node-sass
    > node scripts/install.js
    
    Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node
    Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node": 
    
    HTTP error 404 Not Found
    
    Hint: If github.com is not accessible in your location
          try setting a proxy via HTTP_PROXY, e.g. 
    
          export HTTP_PROXY=http://example.com:1234
    
    or configure npm proxy via
    
          npm config set proxy http://example.com:8080
```

Upon checking https://github.com/sass/node-sass/releases, the file `linux-x64-59_binding.node` doesn't seem to exist.

**Comment by xzyfer** [comment]
Node 9 is not yet supported.

**Comment by tthaliath** [comment]
Getting the same error while running yo tool

$ node --version
v9.0.0
$ npm --version
5.5.1

$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be change
d later. mean
Cloning the MEAN repo.......
? What would you like to call your application? Code snippets
? How would you describe your application? Full-Stack JavaScript with MongoDB, E
xpress, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB,
 Express, AngularJS, Node.js
? What is your company/author name? 
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
Running npm install for you....
This may take a couple minutes.
Error: Command failed: cd mean && npm install
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node": 

HTTP error 404 Not Found

Is it due to missing node v9.0.0 support? what is the latest node version that is fully supported?

**Comment by saper** [comment]
Your node-sass is too old.
