### ISSUE TITLE
Remove dependency on tap-driver

### ISSUE THREAD

**Issue by vineetgorhe** [sass/libsass#2591]
Hi,

tap-driver is a GPL-licensed script whereas libsass is MIT. Is it possible to remove dependency on this script?

Thanks!

**Comment by mgreter** [comment]
Not really if we want to keep `make check` from automake. Although it seems that target has been broken for a long time. Can you elaborate why you think this is an issue? This is an auxiliary script solely used for running the spec tests and should IMHO not violate any license constraints. In fact it is unfortunately recommended by [automake themselves][1] to include this script in ones source repo itself. Since the final LibSass library or any derived work is not based on it, I don't really see an issue to have it included in the source distro, as long as we retain their license header in the said script.

[1]: https://www.gnu.org/software/automake/manual/html_node/Use-TAP-with-the-Automake-test-harness.html

**Comment by vineetgorhe** [comment]
Thanks. It prevents users with strict licensing restrictions from importing this source in their repo to build. If this file isn’t needed at all then perhaps it can be deleted during the import.

**Comment by nsharma1989** [comment]
> Thanks. It prevents users with strict licensing restrictions from importing this source in their repo to build. If this file isn’t needed at all then perhaps it can be deleted during the import.

Hi , is there a way to delete this file during import. I am facing similar problems during license checking.

**Comment by ptommasi** [comment]
This thread is closed, but I'm facing the same issue... I cannot use node-sass since there is the GPL clause in it, lawyers won't allow me (a simple scan will surface the file with the GPL license, which is how I ended up in this thread). I know it's a small use case, but if it's part of a long broken target, it may be worth removing.
