### ISSUE TITLE
Creative Commons Attribution Share Alike 3.0 Licensed Code

### ISSUE THREAD

**Issue by tonymeehan** [sass/libsass#3009]
## Overview 

This issue highlights the use of some [Creative Commons Attribution Share Alike 3.0 licensed code from Stackoverflow](https://stackoverflow.com/help/licensing). This code is likely incompatible with the MIT license. See [this Share Alike compatibility overview](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility) for the specific copy left implications of the CC Attribution Share Alike 3.0 license.

## Incompatible Code

In lines 768 - 801 in sass2scss.cpp:

https://github.com/sass/node-sass/blob/d3aebe72d2735b79e68019b3801000fe8178f18b/src/libsass/src/sass2scss.cpp#L768-L801

Please note the reuse of code from ["Getting std :: ifstream to handle LF, CR, and CRLF?"](https://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf).

Would it make sense to replace these lines of code with content that has a license that is compatible with MIT in a future release?

**Comment by megatrontony** [comment]
Awesome, thank you, @nschonni.

**Comment by mgreter** [comment]
With upcoming LibSass 4.0 this will be no longer an issue for LibSass, as the whole sass parsing will be replaced.
None the less, the sass2scss repo will probably stay up. So I will add a few comments:

It is correct that stack-overflow code is generally considered incompatible with MIT license, but there is also the note of code being to trivial to license. And yes, the mentioned code does exactly what it is supposed to do. If I would rewrite the code, it would pretty much end up in the exact same way as the referenced snippet. And I'd rather let the reference there so people can understand why that code does what it does. Which is probably why OP found it in the first place due to the proper attribution.

Don't get me wrong, licenses are important and IP is something to be protected. I know that oracle and goggle argued over a nine line function for IP. So would it be better if I condensed the code down to 6 lines?

```
std::istream::sentry se(is, true);
std::streambuf* sb = is.rdbuf();
if (sb->sbumpc() == '\n') { return is; }
else if (sb->sbumpc() == '\r') { return sb->sgetc() == '\n' ? sb->sbumpc() : is; }
else if (sb->sbumpc() == EOF) { t.empty() ? is.setstate(std::ios::eofbit) : is; }
else { t += (char)c; }
```

There is nothing I can get rid of, because it will then not behave as it should. I can of course implement the same thing less efficient, but I kinda refuse to do so since I know how it must be implemented. I hope this satisfies the inquiry by @hyandell and if not I sure hope my legal expenses insurance will cover that 🙏
