### ISSUE TITLE
Building libsass using ming32-make only generates .a files.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [sass/libsass#3109]
Following the docs on how to build `libsass`, I ran `mingw32-make -C libsass` and it compiled without errors but the output in the `lib` folder only consists of `libsass.a` & not the `.dll` & `.so` variants. 
Any ideas what may be wrong ?

I am on windows 7 x64 OS.

**Comment by mgreter** [comment]
According to https://github.com/sass/libsass/blob/master/docs/build-with-makefiles.md its
```
BUILD="shared" make ...
```

Since you use mingw32 I assume you are using windows and this works fine on my machine:
```
mingw32-make -j CC=gcc BUILD=shared
```

For a true shared library (for e.g. to work with `pkg-config`) we [advise to use autotools][1] instead!

[1]: https://github.com/sass/libsass/blob/master/docs/build-with-makefiles.md#install-onto-the-system

Please re-open if you can still reproduce, but please give specific versions for OS, make and gcc/clang and what command line interpreter being used (cmd.com or e.g. cygwin bash). Thanks!

**Comment by mgreter** [comment]
OK, unfortunately this seems to be a specific issue with recent mingw:
https://stackoverflow.com/questions/43294488/mingw-g-multiple-definition-of-vsnprintf-when-using-to-string

**Comment by Ultra-Instinct-05** [comment]
Thanks @mgreter. That SO post had a solution whereby installing `mingw32-libmingwex-*` solved the linker issue. Thanks for the help !
