### ISSUE TITLE
Interpolation Issue - Combining Values [$15]

### ISSUE THREAD

**Issue by grayghostvisuals** [sass/libsass#442]
I have a user on my project that [filed an issue in regards to interpolation using libsass w/gulpsass](https://github.com/typeplate/starter-kit/issues/23) so I'm curious if this is a bug within libsass' interpolation as the current method I use works just fine according to the docs and compiling with Ruby.

Here's the code that seems to be the problem…

```scss
@function context-calc($scale, $base, $value) {
  @return ($scale/$base) + $value; // was @return ($scale/$base)#{$value};
}
@function measure-margin($scale, $measure, $value) {
  @return ($measure/$scale) + $value; // was @return ($measure/$scale)#{$value};
}
```

As you can see the commented lines were the original lines that worked just fine when compiling with Ruby otherwise libsass was giving this ``font-size: 32 rem`` as a result.

**Comment by HugoGiraudel** [comment]
Adding to the discussion: appending a unit as a string is a very poor way of converting a unitless number to a length since it results in having a `string` instead of a `number`, preventing any further calculation.

**Comment by mgreter** [comment]
IMHO this is a pretty difficult issue since it involes `parse_list`, which we currently always expect to be at least space separated. I have added a `debugger.hpp` file which contains a `debug_ast` function:

input:
```
foo { bar: (10/10)#{rem}; }
```

output:
```
foo { bar: 1 rem; }
```

debug_ast:
```
Block 0x2630200 0
 Ruleset 0x22652c0 0
  Selector_List 0x26302e0 - -
   Complex_Selector 0x26e6300 - - -> { } <> X < >
    Compound_Selector 0x23993c0 - - <> X < >
     Selector_Reference 0x2991a20 @ref 0
   -Complex_Selector 0x26e61a0 - - -> { } <> X <>
   - Compound_Selector 0x23992d0 - - <> X <>
   -  Type_Selector 0x2991980 <<foo>> - <> X < >
  Declaration 0x2b27dc0 0
   prop: String_Quoted : 0x26e63b0 [bar] < > X <>
   value: List 0x2b27cf0 [Space] [delayed: 0]  [interpolant: 0]
   value:  Binary_Expression 0x26e65c0 [11]
   value:   left:  Textual  [NUMBER]0x26e6460 [10]
   value:   right: Textual  [NUMBER]0x26e6510 [10]
   value:  String_Schema 0x2b30d90 4 {has_interpolants}
   value:   String_Quoted : 0x26e6670 [rem] {delayed} <> X <>
```

As you can see this gets parsed as a space separated list, and that's the reason why it fails! IMHO this needs to be parsed and render completely different, so this doesn't look like an easy fix!

Also consider this example:

input.scss
```
// interpolated-urls
fudge { walnuts: blix"fludge"#{hey now}123; }
```

ruby sass output:
```
fudge { walnuts: blix "fludge"hey now123; }
```

libsass output:
```
fudge { walnuts: blix"fludge"hey now123; }
```

The differences are very subtile and I have no idea yet what the actual rule behind it is (and if it actually makes sense or if it should be considered a ruby sass bug).

**Comment by xzyfer** [comment]
Agreed I've looked into this a couple times and it's non trivial. Ruby Sass handles this my having a separate SassScript parser.

I also think our approach to "everything is a list" is a bit overzealous and is the cause some tricky bugs.

**Comment by mgreter** [comment]
IMO we should re-scope this to Milestone 3.3

**Comment by xzyfer** [comment]
:+1:
