### ISSUE TITLE
Inline Sourcemaps

### ISSUE THREAD

**Issue by mchambaud** [sass/libsass#498]
It would be very nice to have more flexible source maps options available.

Something like this.

auto - relative paths where possible, file URIs elsewhere
file - always absolute file URIs
inline - include the source text in the sourcemap
none- no sourcemaps

**Comment by mgreter** [comment]
I'm going to close this since IMHO the usefull options are already implemented.
I may come around to implement the complete ruby sass option set someday. But until then let's see if there is a need for the not yet implemented options (so please open an new issue if you are really missing some option)!
