### ISSUE TITLE
LibSass Roadmap

### ISSUE THREAD

**Issue by hcatlin** [sass/libsass#521]
I've written up some of my thoughts on libsass compatibilty and plans / goals for each release. Let me know what you think!

https://github.com/sass/libsass/wiki/The-LibSass-Compatibility-Plan

A lot of people ask me about what the goals for the project are and what the plan is... so I decided I should probably write it down instead of keeping it in my head.

/cc @nex3 @chriseppstein @akhleung @xzyfer @andrew @malrase @wonja @imathis

**Comment by HansUXdev** [comment]
Sounds awesome. I had a question though on the overall roadmap for scss as language though.

Lately I've been seeing developers either switch from a pre-processor like scss to a post processor like pleeease (next version) or use both pre-processing and post-processing.

Given that, has there been any talk of incorporating post-processing vendor prefixes or the like into the language itself rather then relying on mixins?

**Comment by xzyfer** [comment]
Hi @HansUXdev. This roadmap is specifically targeted at our goal to reach Ruby sass feature parity.

The Ruby sass project is the reference implementation for all other sass implementations. This means all new features, and feature discussions happen on that project https://github.com/sass/sass. That would be the appropriate place to ask since we don't have much involvement in the direction of the Sass language.

**Comment by mgreter** [comment]
Closing this issue since we the wiki page to document this now!
