### ISSUE TITLE
Support parent selector & in values / and/or interpolations

### ISSUE THREAD

**Issue by gionkunz** [sass/libsass#548]
Hi 

First I'd like to thank you for your awesome work! 

I've put together a small BEM Sass library http://codepen.io/gionkunz/pen/rkswl and there are problems in libsass with the parent selector. It looks like there is an undocumented feature in RubySass that the parent selector & can also be converted to a selector string. I believe internally its a list of lists if I'm not mistaken. So in `.test { .abc, .def { &:before { content: "." } } }`  & would be stored as list of lists `( ( ".test .abc" ) , (".test .def") )`. In RubySass when the parent selector `&` appears where a value is expected it gets converted to a string http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions .

```css
.parent-sel-value {
  font-family: &;
  .parent-sel-interpolation {
    font-family: #{&};
     .parent-sel-value-concat {
        font-family: "Current parent: " + &;
     }
  }
}
```

Gets processed to:

```css
.parent-sel-value {
  font-family: .parent-sel-value;
}
.parent-sel-value .parent-sel-interpolation {
  font-family: .parent-sel-value .parent-sel-interpolation;
}
.parent-sel-value .parent-sel-interpolation .parent-sel-value-concat {
  font-family: "Current parent: .parent-sel-value .parent-sel-interpolation .parent-sel-value-concat";
}
```

This feature is particularly interesting for libraries and frameworks that need to have more control over selectors during nesting. I'd really love to have this in libsass too. 

I did not find any spec in https://github.com/sass/sass-spec concerning this undocumented feature and I'd also help where I can to get this in.

Cheers
Gion

**Comment by ekskimn** [comment]
Hi guys,

I'd like to try to implement this in my own fork but not quite sure how to get the parent selector and then translate that to an expression.

It seems that the if block in parse_simple_selector_sequence in the Parser isn't what I thought.  I thought that that would give me a reference to the parent selector (based on the comments).  If it does, I"m not sure how to reference that in the parse_value method when it tries to parse an assignment statement.

Any help would be appreciated.

Also it seems that Selectors can't be Expressions, which is fine because I can use Selector_Schema to get the string value, right?  I think what I'm really looking for is a way to get the environment/context when the parser is parsing a given statement.

Thanks in advance.

**Comment by xzyfer** [comment]
If you're willing to wait I plan to tackle this over the weekend.

**Comment by ekskimn** [comment]
Thats great news!  Thank you.  Ive spent some trying to figure it out and
have been stymied. I think i will wait till you implement it but the
curiosity is killing me on how to implement it.  I read through the wiki on
how to develop for libsass and i still was not sure how to understand some
of the domain language. Would you mind explaining to me how to implement
this?  The curiosity is killing me.
2015. 1. 20. 오후 8:19에 "Michael Mifsud" <notifications@github.com>님이 작성:

**Comment by xzyfer** [comment]
The general idea is you want want `parse_value` to lex just the `&` symbol (we don't care about selectors) and return a reference selector AST node. Then the visitors will take care of the selector substitution for you.

If you want give it a shot I'll take a look at the PR.

**Comment by ekskimn** [comment]
Thank you~!  So that was my first approach but parse_value returns an expression and I didn't know how to create an Expression from a Selector_Reference.  The AST value isn't accessible from a Selector_Reference  object....

**Comment by ekskimn** [comment]
So I am trying to return this:
      Selector_Reference* sel = new (ctx.mem) Selector_Reference(pstate);
      return new (ctx.mem) Expression(sel->pstate());

And when i output the & reference, I get an empty string.  So I think I must not be returning the correct value....

**Comment by xzyfer** [comment]
Yeah I had a look, it's a little more complicated than expected. You need to expand the `Selector_Reference` with `contextualize`. 

This gets tricky because `parse_value` wants to return an Expression, and Expressions are evaluated in the eval visitor which doesn't know about the selector stack.

Some wire will need to be crossed to get crossed. My gut feeling is that the selector expanding logic will need to be factored out of the `Ruleset` expand visitor into it's own operator.

**Comment by ekskimn** [comment]
Ah, okay so that's what I thought.  I was hoping for a simpler answer, which was simply returning the right value in parse_value, but like you said, there was no way to access the member I needed, or rather, the member simply doesn't exist.

When you say expand the `Selector_Reference` with `contextualize`, what do you mean?  Do you mean have Selector_Reference have a reference to a contextualize member or to inherit from it?

I can work on refactoring the selector expanding logic into its own operator.

**Comment by xzyfer** [comment]
If you take a look at the `Ruleset` operator in the expand visitor you'll
see how selectors are resolved (via the contextualize class). That
resolution process takes the current selector stack and figures out the
value of `&`.

**Comment by ekskimn** [comment]
Wouldn't I have to 

a) make Selector_Reference inherit from Expression
b) Have the expand visitor apply the Contextualize to the Selector_Reference for the Assignment visitor method?

**Comment by xzyfer** [comment]
Unfortunately it's not assignments. The `&` is an expression that evaluates
to a list of selectors. As a result it can be used many places a list can
i.e. assignments, selectors, function arguments

**Comment by ekskimn** [comment]
ah...the spec that was written only seemed to account for the assignment case....so this means that I'd have to apply this to ALL the visitor methods???  that kinda sucks....there should be a better way.

**Comment by xzyfer** [comment]
You should need to create a single operator on the the expand and eval
visitors for handling `Selector` and some wrapper `Expression` node. This
is mostly guess work, I know more when I dig into it.

**Comment by ekskimn** [comment]
Ah, that's what you mean by the stacks being different...the eval visitor is for expressions primarily and the expand visitor is primarily for Statements?

**Comment by xzyfer** [comment]
Exactly. Only the expand visitor know how to hydrate the `&` expression. My
gut feeling is you'll need a new `Expression ` subclass node in the mix.

**Comment by ekskimn** [comment]
Hmm....so there's a dilemma where the expand visitor takes the eval visitor as a constructor parameter because it uses it to eval arguments, which is fine, but if I were to make the eval visitor take the expand visitor as a construction parameter then that would be circular....do I need a new visitor class to submit to both classes?

**Comment by ekskimn** [comment]
Hi xzyfer,

Out of curiosity, did you manage to get to this at all this weekend?

**Comment by xzyfer** [comment]
No I haven't. I forgot it was a long weekend here so I've been away.

**Comment by ekskimn** [comment]
Ah, if i can ask a question...don't want to bother you on your long weekend....but I am trying to implement this and am trying to figure out if I need to do the following:

1. create a parent selector expand visitor that operates on a parent selector expression object and outputs a Statement
2. pass it to the eval visitor and have it execute when it operates on a parent selector expression
3. pass it and the eval visitor to the expand visitor and execute it when operating on a ruleset object and outputs a statement.

would that do the trick?

**Comment by Snugug** [comment]
Running in to this issue too, although in a slightly different syntax: using it inside of if statements.

```scss
$EQ-Selectors: ();

@mixin eq-pts($states) {
  &:before {
    display: none;
    content: '#{str-slice(inspect($states), 2, -2)}';
  }

  @if not index($EQ-Selectors, &) {
    $EQ-Selectors: append($EQ-Selectors, &) !global;
  }
}
```

It's choking on `@if not index($EQ-Selectors, &)` (and if I were to guess, probably the next line too, but doesn't get that far).

**Comment by ekskimn** [comment]
@xzyfer I have the first test case passing, but I can't seem to get the interpolation and the binary expression one going.  When I do a perform(&to_string) on a Compound_Selector, it returns an empty string.  Is that not implemented for Compound_Selector?  What I'm trying to do is in the Eval visitor to evaluate a binary expression and if the right or left is a parent selector, I want to print the string and set it to the value of the String_Constant object it returns.  any ideas?

**Comment by xzyfer** [comment]
Hi @ekskimn, apologies I've been busy with other things.

Could you please open a PR with your current work? That would be the ideal place to discuss implement details.

**Comment by xzyfer** [comment]
@Snugug it would be awesome if you could whip together a sass-spec of the place `&` can be used as a value i.e. interpolation, function arguments, mixin arguments, variable assignments (?)...

**Comment by Snugug** [comment]
@xzyfer Will do.

**Comment by xzyfer** [comment]
Bump. @ekskimn can you please open a PR with your work so far. I'd hate to have to duplicate effort on this.

**Comment by ekskimn** [comment]
Will do this weekend

**Comment by ekskimn** [comment]
@xzyfer
Sorry it's taking a bit.  I'll have  PR to you tonight

**Comment by xzyfer** [comment]
No worries @ekskimn I'm rather pre-occupied myself atm.

We appreciate all your work.

**Comment by ekskimn** [comment]
Hey @xzyfer 
Just to let you know where i am with things...i have the first test case figured out but when the parent selector is in another statement such as an interpolation, i'm having a hard doing that without the contextualizer being in the eval visitor.  The problem is that the contextualizer takes the eval as a parameter.  

What do you recommend?

**Comment by xzyfer** [comment]
I'm sorry but it's just really hard to visualise with out seeing the code
so far. It's perfectly fine to put up a PR that's not perfect.

**Comment by ekskimn** [comment]
PR to you @xzyfer ...like the comments say, i have the declaration and the binary operations working but the interpolation isn't...though it really should and not quite sure why it wouldn't....I'm still looking at that, but if you get a chance take a look at the PR

**Comment by xzyfer** [comment]
Thanks for your work, we really appreciate it. FWIW there's a comprehensive spec suit for this feature now at https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/selectors.

**Comment by gionkunz** [comment]
Awesome!

**Comment by gionkunz** [comment]
Great effort guys :+1:
