### ISSUE TITLE
Support Sass 3.3 scoping

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#613]
Following on from https://github.com/sass/libsass/issues/278 opening this issue to track work on the new scoping model.

Although the Libsass changeset should be easy enough, sass-spec will probably need some significant work.

**Comment by mgreter** [comment]
As a side note: A proper implementation should release the memory of the variable as soon as it goes out of scope (I guess we don't have to deal with references and counting). AFAIK my last tests showed that ruby sass also does not do this, and libsass of course neither yet! This could IMO lead to potential DOS, since a simple very big `@for` loop will allocate at least one additional variable on each iteration. I thought about a memory limit for [ctx.mem] allocations, but for that we would need to have stats about all allocated memory sizes.
