### ISSUE TITLE
Append to a provided source map

### ISSUE THREAD

**Issue by aexmachina** [sass/libsass#668]
It's possible to have source files that have already undergone some preprocessing (this is the common case in broccoli-sass) before they're handed to libsass. In this case it's not possible for libsass to maintain the mapping all the way back to the original source files.

The solution to this is add the ability to provide a source map to libsass which contains the previous mappings, and then libsass would append to this source map with its own transformations.

- What can I do to help make this possible?
- Do we already have the ability to parse a source map into our in-memory structure, or would this need to be added?
- What options would we want for this? Maybe `append_source_map`?

**Comment by mgreter** [comment]
I created a [collective ticket] [1] to keep track this and other "non-urgent" feature requests, in order to keep the issue tracker a bit more clean for the more 1st aid issues. I would like to encourage everybody interested in this particular feature to add their comments into this closed issue anyway.

Thanks for your understanding and your contribution!

[1]: https://github.com/sass/libsass/issues/1892

**Comment by zigotica** [comment]
Hi @mgreter @aexmachina 

Is fixing the Source Map feature in any milestone? I know you might have other priorities, but I'd really love to see it working. This would help fine tune development quite a lot for many teams.

Thank you

**Comment by flops** [comment]
I think this is a close one, correct me if i'm wrong.

https://github.com/sass/node-sass/issues/1584
