### ISSUE TITLE
Change Indenting to Tabs

### ISSUE THREAD

**Issue by AndyF** [sass/libsass#752]
Give the option to change from 2 spaces to tab indenting: https://github.com/sass/node-sass/issues/578#issuecomment-67852958

**Comment by mgreter** [comment]
I have added a commit which should allow implementors to change this. I would consider this alpha since it could introduce subtle edge cases which we are not yet aware of.

**Comment by am11** [comment]
@mgreter, thanks. :+1: 

I will make node-sass v2.0.0 without this feature. Later, we will provide these options on node-sass front: `options.linefeed = "CR/LF/CRLF"`, `options.useTabIndentation = true/false` and `options.indentationLength = whole number (0+)`. Then generate appropriate options for libsass. Also, we will inherit libsass defaults for these, i.e. we will not set default value and let libsass apply its defaults.

**Comment by mgreter** [comment]
I will also not include this in `perl-libsass` 3.1. and will do it the same way as you wrote (with the options). I thought about having all these options directly in libsass, but thought that I should not limit any implementors, since the basic option is really just a "string". I hope you agree on that? Therefore you have to provide a "static string" for this options, pretty much different from other "string" options!

**Comment by am11** [comment]
Yes the string option itself makes sense.
Would we need to dispose these `const char*`, or libsass parser will free the memory after producing the option (like `imports**`)?

**Comment by mgreter** [comment]
Exactly the opposite! Libsass will not free these strings! You have to make sure these strings live as long as the context. I advice implementers to use static strings (const char* lf = "\r\n") for these options. We do not make a copy, as we do with most other small strings (like output_path)!
