### ISSUE TITLE
Indented syntax and quoted @charset 'UTF-8'

### ISSUE THREAD

**Issue by molily** [sass/libsass#845]
When using the indented syntax, `@charset` requires a non-quoted encoding.

Fails:
```
@charset 'UTF-8'
@charset "UTF-8"
```
Gives an error “invalid top-level expression”

Full example: https://gist.github.com/molily/1928a48b89c5d793579c (via Node)

Works:
```
@charset UTF-8
```

Is this deliberate behavior?

In contrast, Ruby Sass accepts these two forms:
```
@charset 'UTF-8'
@charset "UTF-8"
```
… which is what I would expect.

Did I miss something? Thanks in advance. :)

**Comment by am11** [comment]
Nice catch!

test.scss:

```scss
@charset 'UTF-8';

*{
  color: red;
}
```

Produces `* {\n  color: red; }\n`, but with test.sass:

```sass
@charset 'UTF-8'

*
  color: red
```

Throws:

```javascript
{ status: 1,
file: 'c:/temp/test.sass',
line: 1,
column: 18,
message: 'invalid top-level expression',
code: 1 }
```

@xzyfer, is skipping `@charset` directive from emitting into output by design (spec)?

**Comment by xzyfer** [comment]
@am11 `@charset UTF-8` is omitted if there are no utf-8 characters in the output. This is by design.

**Comment by xzyfer** [comment]
@molily thanks for the bug report we'll aim to fix this in 3.2

**Comment by am11** [comment]
@xzyfer, few more notes. It turned out the be the issue at sass2scss conversion step. I placed a breakpoint at [file.cpp#L282](https://github.com/sass/libsass/blob/31521ef3ece636892f395a80392448ceae449b90/file.cpp#L282) and here is what I have found:

**Before (`.sass`):**

```sass
@charset 'UTF-8'

*
  color: red
```

**After (`.scss`):**

```scss
@charset 'UTF-8' {}

* {
  color: red; }
```

**Expected (`.scss`):**

```scss
@charset 'UTF-8';

* {
  color: red; }
```

//cc @mgreter 

(Disclaimer: I am testing with v3.1.0 not the latest master)

**Comment by Baires** [comment]
Any news abut this issue? I'm also stuck

**Comment by molily** [comment]
Thanks a lot for your work. :satisfied:
