### ISSUE TITLE
Separate custom importers into 'custom resolvers' and 'custom readers'?

### ISSUE THREAD

**Issue by callumlocke** [sass/libsass#862]
Custom importers are awesome, but I think they cover two separate use cases, and the overall interface would be more useful if this was split into two different callbacks:

1. custom path resolution – for people who want to control how a statement like `@import 'foo'` gets resolved to a list of potential file paths
2. custom file reading – for people who want to mediate filesystem access (in order to preprocess the SCSS data first, or to load it from a special non-disk location, etc.)

I think splitting custom importers into custom **resolvers** and custom **readers** would be a better separation of concerns in principle, and also give some practical benefits.

I see four sets of users:

1. people who want to control path resolution
2. people who want to provide a custom method to read each file (e.g. so they can preprocess its contents first)
3. people who want to do both these things
4. people who don't want to do either

Group 2 is the one that really benefits from this change. Sass already comes with logic to convert an import string to a list of possible file paths – ie, for `@import 'foo'` it needs to try `./foo.scss`, `./foo.sass`, `./_foo.scss`, `./_foo.sass` – all of the above relative to every configured load path, in some particular order of precedence. I don't want to have to re-implement that logic myself (and maybe get it slightly wrong) in my custom importer. I just want to provide a custom file reader so I can preprocess partial contents on the fly before Sass renders them. I just want Sass to resolve `@import 'foo'` to a list of paths using its default logic, and call my custom reader for each path, until the custom reader returns some contents.

**Comment by mgreter** [comment]
I already had that idea, but it's really a very very low priority for me. IMHO this issue here is only about the file reading part and has not much to do with the custom importers. You already can return back filenames to libsass with custom importers, which libsass will then read like normal imports ("import rewriter").

So I would suggest to open an issue (or rename this one) for "custom readers", as you put it. I don't think removing the possibility to return data right away with custom importers is a good idea. Other than that, I don't see the relation to custom importers.
