### ISSUE TITLE
libsass does not give errors for missing imported base class in @extend

### ISSUE THREAD

**Issue by akshat1** [sass/libsass#871]
Given the following code
<pre><code>
.bar {
  @extend .foo;
  color: green;
}
</code></pre>

ruby-sass gives the following error:
<pre><code>
Error: ".bar" failed to @extend ".foo".
       The selector ".foo" was not found.
       Use "@extend .foo !optional" if the extend should be able to fail.
        on line 4 of bar.scss
  Use --trace for backtrace.
</code></pre>

While libsass (by way of node-sass) gives:
<pre><code>
.bar {
  color: green; }
</code></pre>

This was performed using node-sass (2.0.0-beta). I think libsass should also throw an error instead of proceeding with the compilation. My apologies if I am seeing this incorrectly.

**Comment by yonidor** [comment]
+1 encountered the same issue

**Comment by jananananana** [comment]
+1, using Sass 3.4, seeing same issue

**Comment by xzyfer** [comment]
Thanks for the reports. I'll try to get this into our next release.

**Comment by mgreter** [comment]
This one is also trickier than expected. @xzyfer you added the 3.2 Milestone for this, so do you have an idea how to fix this. I was able to tackle the missing error when extending across media queries, but this one seems more difficult, since extend seems to be run twice, which makes my check in the WIP branch fail on the second run. Otherwise I don't think I can fix this for 3.2!

**Comment by xzyfer** [comment]
@mgreter the way to handle this is by setting metadata on the extends in the cssize visitor. This isn't a difficult fix to the looks of it, I'm just not sure if I'll the time before 3.2.0. I'm pretty much out of action this month.

You can see the Ruby sass implementation in the [cssize visitor](https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/cssize.rb#L108-L129) and the actual error in the [extend visitor](https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/extend.rb#L49-L67).

IMO this is non-critical and can be delayed to 3.3 if it's the only 3.2 blocker.

**Comment by mgreter** [comment]
Rescoping to 3.3, since it is a non trivial refactoring and we consider this issue a minor one, because it only happens with "invalid" input. As a drop-in replacement, libsass does not break, since ruby sass would not create any output anyway! We still consider it a bug, bit will not have a fix in 3.2!

**Comment by xzyfer** [comment]
Rescoped to 3.4 since this doesn't prevent people migrating to LibSass from Ruby Sass.
