### ISSUE TITLE
Segmentation fault using trace

### ISSUE THREAD

**Issue by keoghpe** [sass/libsass#886]
I'm running libsass with grunt (OSX Yosemite) and I'm getting a segmentation fault:

    grunt sass --trace
    Running "sass:dist" (sass) task
    Segmentation fault: 11

This occurs after adding this to my main.scss file:

    img {
      filter: grayscale(0.5);
    }

**Comment by xzyfer** [comment]
Please confirm which version of grunt-sass and node-sass you have.

**Comment by keoghpe** [comment]
grunt-sass: 0.14.2
node-sass: 0.9.3

**Comment by xzyfer** [comment]
That version of node-sass uses a very old version of libsass that is no
longer supported. It's likely this issue has been in fixed in newer
versions. Please update to the latest grunt-sass and try again.

If the latest grunt-sass is not using node-sass 2.0.1 please also open an
issue on their issue tracker suggesting they update.

**Comment by rocco** [comment]
just fyi:
grunt-sass@0.14.2 as used in current yeoman webapp generator uses node-sass: 0.9.3.
update your package.json to "grunt-sass": "^0.18.0" and you're good to go.
