### ISSUE TITLE
Selector groups can not be extended

### ISSUE THREAD

**Issue by aritmico** [sass/libsass#950]
I'm not able to compile something like:

.selector1{ ... }
.selector2{ ... }

.selector3{ @extend .selector1, .selector2; }

According to sass-lang ref-doc:

Multiple extends can also be written using a comma-separated list of selectors. For example, @extend .error, .attention is the same as @extend .error; @extend .attention.

A couple of months ago worked fine and, currently, it compiles well on codepen.

Am I missing something ?

**Comment by mgreter** [comment]
This is the `selector groups may not be extended` error, which is simply a missing feature. I renamed the title since you didn't include this in your report, so the search can find this issue. @xzyfer feel free to assign a milestone, since I think you have more expertise in this area!

**Comment by aritmico** [comment]
Hi @mgreter, 
I can't understand why, a couple of months ago, I was able to compile it.

I wrote an entire fluid grid framework with this feature and now I'm unable to still work on it.

Amazingly weird.

**Comment by aritmico** [comment]
You can close the issue:

**Comment by xzyfer** [comment]
@archgrove thank you for this report. Let me clear a couple things up.

> it compiles well on codepen

Codepen uses Ruby Sass not Libsass which is why your code works there.

> I can't understand why, a couple of months ago, I was able to compile it.

It sounds you were using Ruby Sass, not Libsass. Libsass is not yet at feature parity.

> You can close the issue:
I've reopened this issue because as @mgreter pointed out this is a missing feature. 
We will keep this issue open until it has been added in Libsass.

**Comment by aritmico** [comment]
OMG. What a stupid developer am I ?
I was compiling under mac osx and I installed sass by gem.
This means ruby-sass and that I'm so sorry for opening this issue.

**Comment by hcatlin** [comment]
No big deal! It's fine!

**Comment by hcatlin** [comment]
Sorry, just realized it was requested to stay open above. @xzyfer I'll stop mucking about. ;)

**Comment by mgreter** [comment]
Actually this already works, once we remove the check that throws the error. Made a `blame` check and it was in place since the expand source file was introduced. So I just removed it, added a loop around the existing code and it does the right thing at least in this case. So I would like to ship this with 3.2.0. I honestly have no idea how well the feature is supported, but I guess we'll see :smile:
