### ISSUE TITLE
build artifacts

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#999]
Does libsass store pre-built anywhere?

On CircleCI, there's an option to store build artifacts after all build/test steps have passed. I imagine TravisCI has something similar. This would be super useful for at least linux 64 architecture (and possibly others). Has there been any discussion about providing built libraries?

**Comment by mgreter** [comment]
We do not provide compiled binaries. We expect distributions (like rpms for linux) or implementers (like node-sass) to provide those if necessary. This would rather be a question for `sassc` actually, since libsass would only provide a dynamic library (so or .dll) and nothing really usable on its own.
